language: python
python: "2.7"
sudo: required
services:
  - docker

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - sudo apt-get install jq
  - printf "[defaults]\nroles_path = ../" > ansible.cfg
  - ansible-galaxy install -r requirements.yml
  - docker run --name travis -d dpujadas/baseimage:python2

script:
  # Check the syntax
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Check role success
  - ansible-playbook tests/test.yml -i tests/inventory
  # Check idempotence
  - >
    ansible-playbook tests/test.yml -i tests/inventory | tee /tmp/output.txt;
    grep -q 'changed=0.*failed=0' /tmp/output.txt
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # Check elasticsearch is up and running
  - curl -s "http://$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' travis):9200/_cluster/health?pretty=true" | jq '.status' | grep green