- name: Create runit dir
  file:
    state: 'directory'
    path: '/etc/service/elasticsearch'

- name: Create runit script
  template:
    src: 'runit-script.j2'
    dest: '/etc/service/elasticsearch/run'
    mode: '0755'
